# This file was generated by GoReleaser. DO NOT EDIT.
cask "symbolista" do
  desc "A CLI tool to count occurrances of characters in a directory, with a TUI mode"
  homepage "https://github.com/ogdakke/symbolista"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "symbolista"

  on_macos do
    on_intel do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.1.0/symbolista_Darwin_x86_64.tar.gz"
      sha256 "8da5dd34e61aa8b9b2b73553d286e241eb4a5a7fcca449da6286148fa1e27e48"
    end
    on_arm do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.1.0/symbolista_Darwin_arm64.tar.gz"
      sha256 "237d0d0816ddcd8c0130f8ce5aae73cd2abf57b52ef229de713127e9dff10e31"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.1.0/symbolista_Linux_x86_64.tar.gz"
      sha256 "33bbca1ed8d45106e0638869d4852f95dad43b9d954489a35e1225299db10203"
    end
    on_arm do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.1.0/symbolista_Linux_arm64.tar.gz"
      sha256 "e19952a8fd73f9cb35959e37cb72bfcf048a89426decf65bfa51a4497998c698"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/symbolista"]
    end
  end

  # No zap stanza required
end
