# This file was generated by GoReleaser. DO NOT EDIT.
cask "symbolista" do
  desc "A CLI tool to count occurrances of characters in a directory, with a TUI mode"
  homepage "https://github.com/ogdakke/symbolista"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "symbolista"

  on_macos do
    on_intel do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.2.1/symbolista_Darwin_x86_64.tar.gz"
      sha256 "205f87369673735cf24a665208e1c900978087cdd3eb7e4184f1c2f2be9bb435"
    end
    on_arm do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.2.1/symbolista_Darwin_arm64.tar.gz"
      sha256 "0aaf3c956583597f4791735aabca3ee905d2aa1f0b17e9804fad6dc49d018f6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.2.1/symbolista_Linux_x86_64.tar.gz"
      sha256 "2579a4f3020ad5270ce3173282082ab432bcc484604cd726003e908823721ec8"
    end
    on_arm do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.2.1/symbolista_Linux_arm64.tar.gz"
      sha256 "b8a5ba350124fc0f4b758f062465e973f67388b169f3d9054f35bfef6cc7340e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/symbolista"]
    end
  end

  # No zap stanza required
end
