# This file was generated by GoReleaser. DO NOT EDIT.
cask "symbolista" do
  desc "A CLI tool to count occurrances of characters in a directory, with a TUI mode"
  homepage "https://github.com/ogdakke/symbolista"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "symbolista"

  on_macos do
    on_intel do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.0.9/symbolista_Darwin_x86_64.tar.gz"
      sha256 "42b15b7bf7401f53734c92b0fe04851b48ef2e1fc16a7c6e1095c0a1e67620fe"
    end
    on_arm do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.0.9/symbolista_Darwin_arm64.tar.gz"
      sha256 "1939618280bf3d0985ae6e4b5d0f920ad2759bde36974c89c3a3ddb27b674535"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.0.9/symbolista_Linux_x86_64.tar.gz"
      sha256 "68c60c86bb146bf5382b6b261726d5b054bae1ad9d2926620c4176a9772a3bf2"
    end
    on_arm do
      url "https://github.com/ogdakke/symbolista/releases/download/v0.0.9/symbolista_Linux_arm64.tar.gz"
      sha256 "5fed539b77037fb2aa96e50efd88890bf05a512d136d114d292492c5edbf8427"
    end
  end

  # No zap stanza required
end
